name: bluetooth
version: 1.0
architectures: [armhf, amd64]
vendor: Sejal Chauhan <sejalc@cs.wisc.edu>
summary: bt for rpi2
description: capture ble packets on rpi2
icon: icon.png

parts:
    bluetooth:
        plugin: make
        source: .
        stage-packages:
            - bluez
            - rfkill
